name: Deploy master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn build
      run: |
        yarn install --frozen-lockfile
        yarn build prod
      env:
        GQL_ENDPOINT: https://ames.tirr.dev/graphql
    - name: aws s3 sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --exclude '*.map'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: us-east-1
        SOURCE_DIR: dist
        DEST_DIR: statdiff
